### ISSUE TITLE
Hubic driver raises exceptions

### ISSUE THREAD

**Issue by Khady** [onitu/onitu#90] opened 2014-09-25 15:20 UTC
```
(venv)17:05:34 epitech/onitu rm -rf dbs/*
zsh: sure you want to delete all the files in /Users/louisroche/Code/epitech/onitu/dbs [yn]? y
dbs/example/000029.ldb
dbs/example/000031.ldb
dbs/example/000034.ldb
dbs/example/000037.ldb
dbs/example/000040.ldb
dbs/example/000041.log
dbs/example/000042.ldb
dbs/example/CURRENT
dbs/example/LOCK
dbs/example/LOG
dbs/example/LOG.old
dbs/example/MANIFEST-000039
dbs/example
(venv)17:05:46 epitech/onitu python -m onitu --setup setup-hubic.json
[2014-09-25 15:05] INFO: Onitu: Loading setup...
[2014-09-25 15:05] INFO: Escalator: Starting on 'tcp://127.0.0.1:58945'
2014-09-25 17:05:49 circus[33084] [INFO] Starting the stats streamer
[2014-09-25 15:05] INFO: Referee: Started
[2014-09-25 15:05] INFO: hubic-A: Started
[2014-09-25 15:05] INFO: hubic-B: Started
[2014-09-25 15:05] INFO: REST API: Starting on localhost:3862
[2014-09-25 15:05] INFO: hubic-A - Dealer: Started
[2014-09-25 15:05] INFO: hubic-A - Router: Started
[2014-09-25 15:05] INFO: Referee: Update for '/CUMULUS_Logo.svg' from hubic-A
[2014-09-25 15:05] INFO: Referee: Update for '/arguing.jpg' from hubic-A
[2014-09-25 15:05] INFO: Referee: Update for '/lego.jpeg' from hubic-A
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "onitu/drivers/hubic/hubic.py", line 378, in start
    plug.options['refresh_token'], root)
  File "onitu/drivers/hubic/hubic.py", line 30, in __init__
    self._get_openstack_credentials()
  File "onitu/drivers/hubic/hubic.py", line 60, in _get_openstack_credentials
    'account/credentials').json()
  File "onitu/drivers/hubic/hubic.py", line 93, in _hubic_call
    headers, limit)
  File "onitu/drivers/hubic/hubic.py", line 79, in _hubic_renew_token
    return self._hubic_call(method, uri, data, headers, limit)
  File "onitu/drivers/hubic/hubic.py", line 88, in _hubic_call
    json = result.json()
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/requests/models.py", line 776, in json
    return json.loads(self.text, **kwargs)
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/simplejson/__init__.py", line 501, in loads
    return _default_decoder.decode(s)
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2014-09-25 15:06] INFO: hubic-B: Exited
2014-09-25 17:06:03 circus[33084] [ERROR] Failed to get info for 33087. (pid=33087)
Traceback (most recent call last):
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/circus/stats/collector.py", line 75, in collect_stats
    info = util.get_info(pid)
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/circus/util.py", line 259, in get_info
    raw_cmdline = get_cmdline(process)
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/circus/process.py", line 85, in get_cmdline
    return proc.cmdline()
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/psutil/__init__.py", line 551, in cmdline
    return self._proc.cmdline()
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/psutil/_psosx.py", line 191, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: (pid=33087)
[2014-09-25 15:06] INFO: hubic-B: Started
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "onitu/drivers/hubic/hubic.py", line 378, in start
    plug.options['refresh_token'], root)
  File "onitu/drivers/hubic/hubic.py", line 30, in __init__
    self._get_openstack_credentials()
  File "onitu/drivers/hubic/hubic.py", line 60, in _get_openstack_credentials
    'account/credentials').json()
  File "onitu/drivers/hubic/hubic.py", line 88, in _hubic_call
    json = result.json()
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/requests/models.py", line 776, in json
    return json.loads(self.text, **kwargs)
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/simplejson/__init__.py", line 501, in loads
    return _default_decoder.decode(s)
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/louisroche/Code/epitech/onitu/venv/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2014-09-25 15:06] INFO: hubic-B: Exited
[2014-09-25 15:06] INFO: hubic-B: Started
^C[2014-09-25 15:06] INFO: Onitu: Exiting...
[2014-09-25 15:06] INFO: Escalator: Exited
[2014-09-25 15:06] INFO: Referee: Exited
[2014-09-25 15:06] INFO: hubic-A: Exited
[2014-09-25 15:06] ERROR: hubic-B - Router: Unexpected error: Operation not supported
Exception in thread hubic-B:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "onitu/plug/router.py", line 50, in run
    self.router.close(linger=0)
AttributeError: 'NoneType' object has no attribute 'close'

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "onitu/drivers/hubic/hubic.py", line 385, in start
    plug.listen()
  File "onitu/plug/plug.py", line 93, in listen
    self.dealer.resume_transfers()
  File "onitu/plug/dealer.py", line 76, in resume_transfers
    prefix='entry:{}:transfer:'.format(self.name)
  File "onitu/escalator/client/escalator.py", line 111, in range
    for key, value in values]
TypeError: 'NoneType' object is not iterable

[2014-09-25 15:06] INFO: hubic-B: Exited
(venv)17:06:11 epitech/onitu Exception in thread hubic-B:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "onitu/plug/router.py", line 50, in run
    self.router.close(linger=0)
AttributeError: 'NoneType' object has no attribute 'close'

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "onitu/drivers/hubic/hubic.py", line 385, in start
    plug.listen()
  File "onitu/plug/plug.py", line 93, in listen
    self.dealer.resume_transfers()
  File "onitu/plug/dealer.py", line 76, in resume_transfers
    prefix='entry:{}:transfer:'.format(self.name)
  File "onitu/escalator/client/escalator.py", line 111, in range
    for key, value in values]
TypeError: 'NoneType' object is not iterable

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "onitu/drivers/hubic/hubic.py", line 197, in run
    self.check_changes()
  File "onitu/drivers/hubic/hubic.py", line 174, in check_changes
    metadata = plug.get_metadata(filename)
  File "onitu/plug/plug.py", line 173, in get_metadata
    metadata = Metadata.get_by_filename(self, filename)
  File "onitu/plug/metadata.py", line 65, in get_by_filename
    return cls.get_by_id(plug, fid)
  File "onitu/plug/metadata.py", line 72, in get_by_id
    values = plug.escalator.get('file:{}'.format(fid), default=None)
  File "onitu/escalator/client/escalator.py", line 75, in get
    value = self._request(protocol.cmd.GET, key)[0]
  File "onitu/escalator/client/escalator.py", line 29, in _request
    *args))
  File "socket.pyx", line 571, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5319)
  File "socket.pyx", line 608, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5008)
  File "socket.pyx", line 96, in zmq.backend.cython.socket._check_closed (zmq/backend/cython/socket.c:1370)
ZMQError: Socket operation on non-socket
```

My setup

```
{
  "name": "example",

  "entries": {
        "hubic-A": {
              "driver": "hubic",
              "options": {
                    "root": "/onitu-A",
                    "refresh_token": "",
                    "client_id": "",
                    "client_secret": "",
                    "changes_timer" : 10
              }
        },
        "hubic-B": {
              "driver": "hubic",
              "options": {
                    "root": "/onitu-B",
                    "refresh_token": "",
                    "client_id": "",
                    "client_secret": "",
                    "changes_timer" : 10
              }
        }
  },

  "rules": [
    {
      "match": {"path": "/"},
      "sync": ["hubic-A", "hubic-B"]
    }
  ]

}
```

**Comment by Khady** [comment] 2014-09-25 21:08
I only have the problem with an empty DB.

**Comment by Akiat** [comment] 2014-09-27 15:46
I'm not able to reproduce this bug, someone else has this issue ?

**Comment by k4nar** [comment] 2014-10-16 17:59
Any news on that one ?

**Comment by k4nar** [comment] 2014-10-27 23:43
@Khady : Do you know if this issue is still present ?

**Comment by Khady** [comment] 2014-10-28 21:16
I tried last week and had no problem.

**Comment by k4nar** [comment] 2014-10-29 08:07
I'm closing it, we will re-open it if we see that problem again.

**Closed as completed by k4nar** 2014-10-29 08:07 UTC
Labels: bug, P-high
